modLoader = "javafml"
loaderVersion = "[34,)"
license = "https://github.com/teamhollow/direbats/blob/HEAD/LICENSE"
[[mods]]

modId = "direbats"
displayName = "Direbats"
description='''
    Description
'''
authors = "Team Hollow"
logoFile="pack.png"

version = "${file.jarVersion}"
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://teamhollow.net/data/update/direbats.json"

displayURL="https://direbats.teamhollow.net"
issueTrackerURL = "https://github.com/teamhollow/direbats/issues"

[[dependencies.direbat]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.direbat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
