modLoader = "javafml"
loaderVersion = "[32,)"
[[mods]]

modId = "direbats"
displayName = "Direbats"
description='''
    Description
'''
authors = "Team Hollow"
logoFile="pack.png"

version = "${file.jarVersion}"
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/"

displayURL="https://direbats.teamhollow.net"
issueTrackerURL = "https://github.com/teamhollow/direbats/issues"
license = "https://github.com/teamhollow/direbats/blob/master/LICENSE"

[[dependencies.direbat]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.108,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.direbat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
